# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  telegram:
    bot:
      token: '337965642:AAGGCLG7VoHL9VuvqXl6MY_dtO0lp9OaC2U'
      username: ZhurinSupportBot
  secret_key_base: c259cdca108fc7785f7293be5efb439642589b19d45720d084d5a62897f81515aa96f3c97a44a955471726643b0a570977bf5cddf96b52374fa05a723a804531

test:
  secret_key_base: a39cc3a4700e4222d60e66ecef8561a624d68bf07632b538460498c8ee1348d0c338fc597b95325c1b83c377ca7fc114c05fb4983f35a92a56a00c05301f5073

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

